// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreadProfile int32

const (
	ThreadProfile_THREAD_PROFILE_UNSPECIFIED ThreadProfile = 0
	ThreadProfile_THREAD_PROFILE_AGENT       ThreadProfile = 1
	ThreadProfile_THREAD_PROFILE_CUSTOMER    ThreadProfile = 2
)

// Enum value maps for ThreadProfile.
var (
	ThreadProfile_name = map[int32]string{
		0: "THREAD_PROFILE_UNSPECIFIED",
		1: "THREAD_PROFILE_AGENT",
		2: "THREAD_PROFILE_CUSTOMER",
	}
	ThreadProfile_value = map[string]int32{
		"THREAD_PROFILE_UNSPECIFIED": 0,
		"THREAD_PROFILE_AGENT":       1,
		"THREAD_PROFILE_CUSTOMER":    2,
	}
)

func (x ThreadProfile) Enum() *ThreadProfile {
	p := new(ThreadProfile)
	*p = x
	return p
}

func (x ThreadProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreadProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_ai_proto_enumTypes[0].Descriptor()
}

func (ThreadProfile) Type() protoreflect.EnumType {
	return &file_proto_ai_ai_proto_enumTypes[0]
}

func (x ThreadProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreadProfile.Descriptor instead.
func (ThreadProfile) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{0}
}

type ThreadMessageRole int32

const (
	ThreadMessageRole_THREAD_MESSAGE_ROLE_UNSPECIFIED ThreadMessageRole = 0
	ThreadMessageRole_THREAD_MESSAGE_ROLE_USER        ThreadMessageRole = 1
	ThreadMessageRole_THREAD_MESSAGE_ROLE_ASSISTANT   ThreadMessageRole = 2
)

// Enum value maps for ThreadMessageRole.
var (
	ThreadMessageRole_name = map[int32]string{
		0: "THREAD_MESSAGE_ROLE_UNSPECIFIED",
		1: "THREAD_MESSAGE_ROLE_USER",
		2: "THREAD_MESSAGE_ROLE_ASSISTANT",
	}
	ThreadMessageRole_value = map[string]int32{
		"THREAD_MESSAGE_ROLE_UNSPECIFIED": 0,
		"THREAD_MESSAGE_ROLE_USER":        1,
		"THREAD_MESSAGE_ROLE_ASSISTANT":   2,
	}
)

func (x ThreadMessageRole) Enum() *ThreadMessageRole {
	p := new(ThreadMessageRole)
	*p = x
	return p
}

func (x ThreadMessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreadMessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ai_ai_proto_enumTypes[1].Descriptor()
}

func (ThreadMessageRole) Type() protoreflect.EnumType {
	return &file_proto_ai_ai_proto_enumTypes[1]
}

func (x ThreadMessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreadMessageRole.Descriptor instead.
func (ThreadMessageRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{1}
}

type Thread struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,3,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,4,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	MessageCount     int32                  `protobuf:"varint,6,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Messages         []*ThreadMessage       `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *Thread) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Thread) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Thread) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *Thread) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

func (x *Thread) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Thread) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Thread) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Thread) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Thread) GetMessages() []*ThreadMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ThreadMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile       ThreadProfile          `protobuf:"varint,4,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	Role          ThreadMessageRole      `protobuf:"varint,5,opt,name=role,proto3,enum=ai.ThreadMessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadMessage) Reset() {
	*x = ThreadMessage{}
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadMessage) ProtoMessage() {}

func (x *ThreadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadMessage.ProtoReflect.Descriptor instead.
func (*ThreadMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ThreadMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThreadMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *ThreadMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadMessage) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *ThreadMessage) GetRole() ThreadMessageRole {
	if x != nil {
		return x.Role
	}
	return ThreadMessageRole_THREAD_MESSAGE_ROLE_UNSPECIFIED
}

func (x *ThreadMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ThreadMessage) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ThreadMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetOrCreateThreadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,3,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrCreateThreadRequest) Reset() {
	*x = GetOrCreateThreadRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateThreadRequest) ProtoMessage() {}

func (x *GetOrCreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateThreadRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrCreateThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrCreateThreadRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *GetOrCreateThreadRequest) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

func (x *GetOrCreateThreadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetThreadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,3,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	MessageLimit     int32                  `protobuf:"varint,4,opt,name=message_limit,json=messageLimit,proto3" json:"message_limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GetThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetThreadRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *GetThreadRequest) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

func (x *GetThreadRequest) GetMessageLimit() int32 {
	if x != nil {
		return x.MessageLimit
	}
	return 0
}

type ListThreadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile       ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsRequest) Reset() {
	*x = ListThreadsRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsRequest) ProtoMessage() {}

func (x *ListThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsRequest.ProtoReflect.Descriptor instead.
func (*ListThreadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ListThreadsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListThreadsRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *ListThreadsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListThreadsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type AppendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,3,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	Role             ThreadMessageRole      `protobuf:"varint,4,opt,name=role,proto3,enum=ai.ThreadMessageRole" json:"role,omitempty"`
	Content          string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,6,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppendMessageRequest) Reset() {
	*x = AppendMessageRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMessageRequest) ProtoMessage() {}

func (x *AppendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMessageRequest.ProtoReflect.Descriptor instead.
func (*AppendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AppendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppendMessageRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *AppendMessageRequest) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

func (x *AppendMessageRequest) GetRole() ThreadMessageRole {
	if x != nil {
		return x.Role
	}
	return ThreadMessageRole_THREAD_MESSAGE_ROLE_UNSPECIFIED
}

func (x *AppendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppendMessageRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ReplaceThreadMessagesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,3,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	Messages         []*NewThreadMessage    `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplaceThreadMessagesRequest) Reset() {
	*x = ReplaceThreadMessagesRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceThreadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceThreadMessagesRequest) ProtoMessage() {}

func (x *ReplaceThreadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceThreadMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReplaceThreadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ReplaceThreadMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplaceThreadMessagesRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *ReplaceThreadMessagesRequest) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

func (x *ReplaceThreadMessagesRequest) GetMessages() []*NewThreadMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type NewThreadMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          ThreadMessageRole      `protobuf:"varint,1,opt,name=role,proto3,enum=ai.ThreadMessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewThreadMessage) Reset() {
	*x = NewThreadMessage{}
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewThreadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewThreadMessage) ProtoMessage() {}

func (x *NewThreadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewThreadMessage.ProtoReflect.Descriptor instead.
func (*NewThreadMessage) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *NewThreadMessage) GetRole() ThreadMessageRole {
	if x != nil {
		return x.Role
	}
	return ThreadMessageRole_THREAD_MESSAGE_ROLE_UNSPECIFIED
}

func (x *NewThreadMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewThreadMessage) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type DeleteThreadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Profile          ThreadProfile          `protobuf:"varint,2,opt,name=profile,proto3,enum=ai.ThreadProfile" json:"profile,omitempty"`
	ExternalThreadId string                 `protobuf:"bytes,3,opt,name=external_thread_id,json=externalThreadId,proto3" json:"external_thread_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteThreadRequest) GetProfile() ThreadProfile {
	if x != nil {
		return x.Profile
	}
	return ThreadProfile_THREAD_PROFILE_UNSPECIFIED
}

func (x *DeleteThreadRequest) GetExternalThreadId() string {
	if x != nil {
		return x.ExternalThreadId
	}
	return ""
}

type ThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *Thread                `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Errors        []*Error               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadResponse) Reset() {
	*x = ThreadResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadResponse) ProtoMessage() {}

func (x *ThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadResponse.ProtoReflect.Descriptor instead.
func (*ThreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{9}
}

func (x *ThreadResponse) GetThread() *Thread {
	if x != nil {
		return x.Thread
	}
	return nil
}

func (x *ThreadResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Errors        []*Error               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThreadsResponse) Reset() {
	*x = ListThreadsResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThreadsResponse) ProtoMessage() {}

func (x *ListThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThreadsResponse.ProtoReflect.Descriptor instead.
func (*ListThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{10}
}

func (x *ListThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ListThreadsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListThreadsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ThreadMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ThreadMessage         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []*Error               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadMessageResponse) Reset() {
	*x = ThreadMessageResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadMessageResponse) ProtoMessage() {}

func (x *ThreadMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadMessageResponse.ProtoReflect.Descriptor instead.
func (*ThreadMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{11}
}

func (x *ThreadMessageResponse) GetMessage() *ThreadMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ThreadMessageResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Errors        []*Error               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadResponse) Reset() {
	*x = DeleteThreadResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadResponse) ProtoMessage() {}

func (x *DeleteThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadResponse.ProtoReflect.Descriptor instead.
func (*DeleteThreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteThreadResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteThreadResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_ai_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{13}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_ai_ai_proto protoreflect.FileDescriptor

const file_proto_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ai/ai.proto\x12\x02ai\"\xb4\x02\n" +
	"\x06Thread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x03 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x04 \x01(\tR\x10externalThreadId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12#\n" +
	"\rmessage_count\x18\x06 \x01(\x05R\fmessageCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12-\n" +
	"\bmessages\x18\t \x03(\v2\x11.ai.ThreadMessageR\bmessages\"\x8b\x02\n" +
	"\rThreadMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x04 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12)\n" +
	"\x04role\x18\x05 \x01(\x0e2\x15.ai.ThreadMessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xa4\x01\n" +
	"\x18GetOrCreateThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x03 \x01(\tR\x10externalThreadId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xab\x01\n" +
	"\x10GetThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x03 \x01(\tR\x10externalThreadId\x12#\n" +
	"\rmessage_limit\x18\x04 \x01(\x05R\fmessageLimit\"\x96\x01\n" +
	"\x12ListThreadsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xf4\x01\n" +
	"\x14AppendMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x03 \x01(\tR\x10externalThreadId\x12)\n" +
	"\x04role\x18\x04 \x01(\x0e2\x15.ai.ThreadMessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\x06 \x01(\tR\fmetadataJson\"\xc4\x01\n" +
	"\x1cReplaceThreadMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x03 \x01(\tR\x10externalThreadId\x120\n" +
	"\bmessages\x18\x04 \x03(\v2\x14.ai.NewThreadMessageR\bmessages\"|\n" +
	"\x10NewThreadMessage\x12)\n" +
	"\x04role\x18\x01 \x01(\x0e2\x15.ai.ThreadMessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"\x89\x01\n" +
	"\x13DeleteThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\aprofile\x18\x02 \x01(\x0e2\x11.ai.ThreadProfileR\aprofile\x12,\n" +
	"\x12external_thread_id\x18\x03 \x01(\tR\x10externalThreadId\"W\n" +
	"\x0eThreadResponse\x12\"\n" +
	"\x06thread\x18\x01 \x01(\v2\n" +
	".ai.ThreadR\x06thread\x12!\n" +
	"\x06errors\x18\x02 \x03(\v2\t.ai.ErrorR\x06errors\"\x86\x01\n" +
	"\x13ListThreadsResponse\x12$\n" +
	"\athreads\x18\x01 \x03(\v2\n" +
	".ai.ThreadR\athreads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12!\n" +
	"\x06errors\x18\x03 \x03(\v2\t.ai.ErrorR\x06errors\"g\n" +
	"\x15ThreadMessageResponse\x12+\n" +
	"\amessage\x18\x01 \x01(\v2\x11.ai.ThreadMessageR\amessage\x12!\n" +
	"\x06errors\x18\x02 \x03(\v2\t.ai.ErrorR\x06errors\"S\n" +
	"\x14DeleteThreadResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\x12!\n" +
	"\x06errors\x18\x02 \x03(\v2\t.ai.ErrorR\x06errors\"=\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*f\n" +
	"\rThreadProfile\x12\x1e\n" +
	"\x1aTHREAD_PROFILE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14THREAD_PROFILE_AGENT\x10\x01\x12\x1b\n" +
	"\x17THREAD_PROFILE_CUSTOMER\x10\x02*y\n" +
	"\x11ThreadMessageRole\x12#\n" +
	"\x1fTHREAD_MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18THREAD_MESSAGE_ROLE_USER\x10\x01\x12!\n" +
	"\x1dTHREAD_MESSAGE_ROLE_ASSISTANT\x10\x022\xb3\x03\n" +
	"\x0fAIThreadService\x12G\n" +
	"\x11GetOrCreateThread\x12\x1c.ai.GetOrCreateThreadRequest\x1a\x12.ai.ThreadResponse\"\x00\x127\n" +
	"\tGetThread\x12\x14.ai.GetThreadRequest\x1a\x12.ai.ThreadResponse\"\x00\x12@\n" +
	"\vListThreads\x12\x16.ai.ListThreadsRequest\x1a\x17.ai.ListThreadsResponse\"\x00\x12F\n" +
	"\rAppendMessage\x12\x18.ai.AppendMessageRequest\x1a\x19.ai.ThreadMessageResponse\"\x00\x12O\n" +
	"\x15ReplaceThreadMessages\x12 .ai.ReplaceThreadMessagesRequest\x1a\x12.ai.ThreadResponse\"\x00\x12C\n" +
	"\fDeleteThread\x12\x17.ai.DeleteThreadRequest\x1a\x18.ai.DeleteThreadResponse\"\x00BHZFgithub.com/kaansari/ceerat-platform/packages/ceerat-contracts/proto/aib\x06proto3"

var (
	file_proto_ai_ai_proto_rawDescOnce sync.Once
	file_proto_ai_ai_proto_rawDescData []byte
)

func file_proto_ai_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)))
	})
	return file_proto_ai_ai_proto_rawDescData
}

var file_proto_ai_ai_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_ai_ai_proto_goTypes = []any{
	(ThreadProfile)(0),                   // 0: ai.ThreadProfile
	(ThreadMessageRole)(0),               // 1: ai.ThreadMessageRole
	(*Thread)(nil),                       // 2: ai.Thread
	(*ThreadMessage)(nil),                // 3: ai.ThreadMessage
	(*GetOrCreateThreadRequest)(nil),     // 4: ai.GetOrCreateThreadRequest
	(*GetThreadRequest)(nil),             // 5: ai.GetThreadRequest
	(*ListThreadsRequest)(nil),           // 6: ai.ListThreadsRequest
	(*AppendMessageRequest)(nil),         // 7: ai.AppendMessageRequest
	(*ReplaceThreadMessagesRequest)(nil), // 8: ai.ReplaceThreadMessagesRequest
	(*NewThreadMessage)(nil),             // 9: ai.NewThreadMessage
	(*DeleteThreadRequest)(nil),          // 10: ai.DeleteThreadRequest
	(*ThreadResponse)(nil),               // 11: ai.ThreadResponse
	(*ListThreadsResponse)(nil),          // 12: ai.ListThreadsResponse
	(*ThreadMessageResponse)(nil),        // 13: ai.ThreadMessageResponse
	(*DeleteThreadResponse)(nil),         // 14: ai.DeleteThreadResponse
	(*Error)(nil),                        // 15: ai.Error
}
var file_proto_ai_ai_proto_depIdxs = []int32{
	0,  // 0: ai.Thread.profile:type_name -> ai.ThreadProfile
	3,  // 1: ai.Thread.messages:type_name -> ai.ThreadMessage
	0,  // 2: ai.ThreadMessage.profile:type_name -> ai.ThreadProfile
	1,  // 3: ai.ThreadMessage.role:type_name -> ai.ThreadMessageRole
	0,  // 4: ai.GetOrCreateThreadRequest.profile:type_name -> ai.ThreadProfile
	0,  // 5: ai.GetThreadRequest.profile:type_name -> ai.ThreadProfile
	0,  // 6: ai.ListThreadsRequest.profile:type_name -> ai.ThreadProfile
	0,  // 7: ai.AppendMessageRequest.profile:type_name -> ai.ThreadProfile
	1,  // 8: ai.AppendMessageRequest.role:type_name -> ai.ThreadMessageRole
	0,  // 9: ai.ReplaceThreadMessagesRequest.profile:type_name -> ai.ThreadProfile
	9,  // 10: ai.ReplaceThreadMessagesRequest.messages:type_name -> ai.NewThreadMessage
	1,  // 11: ai.NewThreadMessage.role:type_name -> ai.ThreadMessageRole
	0,  // 12: ai.DeleteThreadRequest.profile:type_name -> ai.ThreadProfile
	2,  // 13: ai.ThreadResponse.thread:type_name -> ai.Thread
	15, // 14: ai.ThreadResponse.errors:type_name -> ai.Error
	2,  // 15: ai.ListThreadsResponse.threads:type_name -> ai.Thread
	15, // 16: ai.ListThreadsResponse.errors:type_name -> ai.Error
	3,  // 17: ai.ThreadMessageResponse.message:type_name -> ai.ThreadMessage
	15, // 18: ai.ThreadMessageResponse.errors:type_name -> ai.Error
	15, // 19: ai.DeleteThreadResponse.errors:type_name -> ai.Error
	4,  // 20: ai.AIThreadService.GetOrCreateThread:input_type -> ai.GetOrCreateThreadRequest
	5,  // 21: ai.AIThreadService.GetThread:input_type -> ai.GetThreadRequest
	6,  // 22: ai.AIThreadService.ListThreads:input_type -> ai.ListThreadsRequest
	7,  // 23: ai.AIThreadService.AppendMessage:input_type -> ai.AppendMessageRequest
	8,  // 24: ai.AIThreadService.ReplaceThreadMessages:input_type -> ai.ReplaceThreadMessagesRequest
	10, // 25: ai.AIThreadService.DeleteThread:input_type -> ai.DeleteThreadRequest
	11, // 26: ai.AIThreadService.GetOrCreateThread:output_type -> ai.ThreadResponse
	11, // 27: ai.AIThreadService.GetThread:output_type -> ai.ThreadResponse
	12, // 28: ai.AIThreadService.ListThreads:output_type -> ai.ListThreadsResponse
	13, // 29: ai.AIThreadService.AppendMessage:output_type -> ai.ThreadMessageResponse
	11, // 30: ai.AIThreadService.ReplaceThreadMessages:output_type -> ai.ThreadResponse
	14, // 31: ai.AIThreadService.DeleteThread:output_type -> ai.DeleteThreadResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_proto_init() }
func file_proto_ai_ai_proto_init() {
	if File_proto_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_proto_depIdxs,
		EnumInfos:         file_proto_ai_ai_proto_enumTypes,
		MessageInfos:      file_proto_ai_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_proto = out.File
	file_proto_ai_ai_proto_goTypes = nil
	file_proto_ai_ai_proto_depIdxs = nil
}
