// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: proto/ai/ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AIThreadServiceClient is the client API for AIThreadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIThreadServiceClient interface {
	GetOrCreateThread(ctx context.Context, in *GetOrCreateThreadRequest, opts ...grpc.CallOption) (*ThreadResponse, error)
	GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*ThreadResponse, error)
	ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsResponse, error)
	AppendMessage(ctx context.Context, in *AppendMessageRequest, opts ...grpc.CallOption) (*ThreadMessageResponse, error)
	ReplaceThreadMessages(ctx context.Context, in *ReplaceThreadMessagesRequest, opts ...grpc.CallOption) (*ThreadResponse, error)
	DeleteThread(ctx context.Context, in *DeleteThreadRequest, opts ...grpc.CallOption) (*DeleteThreadResponse, error)
}

type aIThreadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIThreadServiceClient(cc grpc.ClientConnInterface) AIThreadServiceClient {
	return &aIThreadServiceClient{cc}
}

func (c *aIThreadServiceClient) GetOrCreateThread(ctx context.Context, in *GetOrCreateThreadRequest, opts ...grpc.CallOption) (*ThreadResponse, error) {
	out := new(ThreadResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/GetOrCreateThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIThreadServiceClient) GetThread(ctx context.Context, in *GetThreadRequest, opts ...grpc.CallOption) (*ThreadResponse, error) {
	out := new(ThreadResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/GetThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIThreadServiceClient) ListThreads(ctx context.Context, in *ListThreadsRequest, opts ...grpc.CallOption) (*ListThreadsResponse, error) {
	out := new(ListThreadsResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/ListThreads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIThreadServiceClient) AppendMessage(ctx context.Context, in *AppendMessageRequest, opts ...grpc.CallOption) (*ThreadMessageResponse, error) {
	out := new(ThreadMessageResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/AppendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIThreadServiceClient) ReplaceThreadMessages(ctx context.Context, in *ReplaceThreadMessagesRequest, opts ...grpc.CallOption) (*ThreadResponse, error) {
	out := new(ThreadResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/ReplaceThreadMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIThreadServiceClient) DeleteThread(ctx context.Context, in *DeleteThreadRequest, opts ...grpc.CallOption) (*DeleteThreadResponse, error) {
	out := new(DeleteThreadResponse)
	err := c.cc.Invoke(ctx, "/ai.AIThreadService/DeleteThread", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIThreadServiceServer is the server API for AIThreadService service.
// All implementations must embed UnimplementedAIThreadServiceServer
// for forward compatibility
type AIThreadServiceServer interface {
	GetOrCreateThread(context.Context, *GetOrCreateThreadRequest) (*ThreadResponse, error)
	GetThread(context.Context, *GetThreadRequest) (*ThreadResponse, error)
	ListThreads(context.Context, *ListThreadsRequest) (*ListThreadsResponse, error)
	AppendMessage(context.Context, *AppendMessageRequest) (*ThreadMessageResponse, error)
	ReplaceThreadMessages(context.Context, *ReplaceThreadMessagesRequest) (*ThreadResponse, error)
	DeleteThread(context.Context, *DeleteThreadRequest) (*DeleteThreadResponse, error)
	mustEmbedUnimplementedAIThreadServiceServer()
}

// UnimplementedAIThreadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIThreadServiceServer struct {
}

func (UnimplementedAIThreadServiceServer) GetOrCreateThread(context.Context, *GetOrCreateThreadRequest) (*ThreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrCreateThread not implemented")
}
func (UnimplementedAIThreadServiceServer) GetThread(context.Context, *GetThreadRequest) (*ThreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThread not implemented")
}
func (UnimplementedAIThreadServiceServer) ListThreads(context.Context, *ListThreadsRequest) (*ListThreadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListThreads not implemented")
}
func (UnimplementedAIThreadServiceServer) AppendMessage(context.Context, *AppendMessageRequest) (*ThreadMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendMessage not implemented")
}
func (UnimplementedAIThreadServiceServer) ReplaceThreadMessages(context.Context, *ReplaceThreadMessagesRequest) (*ThreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceThreadMessages not implemented")
}
func (UnimplementedAIThreadServiceServer) DeleteThread(context.Context, *DeleteThreadRequest) (*DeleteThreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteThread not implemented")
}
func (UnimplementedAIThreadServiceServer) mustEmbedUnimplementedAIThreadServiceServer() {}

// UnsafeAIThreadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIThreadServiceServer will
// result in compilation errors.
type UnsafeAIThreadServiceServer interface {
	mustEmbedUnimplementedAIThreadServiceServer()
}

func RegisterAIThreadServiceServer(s grpc.ServiceRegistrar, srv AIThreadServiceServer) {
	s.RegisterService(&AIThreadService_ServiceDesc, srv)
}

func _AIThreadService_GetOrCreateThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).GetOrCreateThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/GetOrCreateThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).GetOrCreateThread(ctx, req.(*GetOrCreateThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIThreadService_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/GetThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).GetThread(ctx, req.(*GetThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIThreadService_ListThreads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListThreadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).ListThreads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/ListThreads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).ListThreads(ctx, req.(*ListThreadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIThreadService_AppendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).AppendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/AppendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).AppendMessage(ctx, req.(*AppendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIThreadService_ReplaceThreadMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceThreadMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).ReplaceThreadMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/ReplaceThreadMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).ReplaceThreadMessages(ctx, req.(*ReplaceThreadMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIThreadService_DeleteThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteThreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIThreadServiceServer).DeleteThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIThreadService/DeleteThread",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIThreadServiceServer).DeleteThread(ctx, req.(*DeleteThreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIThreadService_ServiceDesc is the grpc.ServiceDesc for AIThreadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIThreadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIThreadService",
	HandlerType: (*AIThreadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateThread",
			Handler:    _AIThreadService_GetOrCreateThread_Handler,
		},
		{
			MethodName: "GetThread",
			Handler:    _AIThreadService_GetThread_Handler,
		},
		{
			MethodName: "ListThreads",
			Handler:    _AIThreadService_ListThreads_Handler,
		},
		{
			MethodName: "AppendMessage",
			Handler:    _AIThreadService_AppendMessage_Handler,
		},
		{
			MethodName: "ReplaceThreadMessages",
			Handler:    _AIThreadService_ReplaceThreadMessages_Handler,
		},
		{
			MethodName: "DeleteThread",
			Handler:    _AIThreadService_DeleteThread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai/ai.proto",
}
