// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: proto/service/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceManagerClient is the client API for ServiceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceManagerClient interface {
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
	BatchUpsertProducts(ctx context.Context, in *BatchUpsertProductsRequest, opts ...grpc.CallOption) (*BatchUpsertProductsResponse, error)
	CreateProductCategory(ctx context.Context, in *CreateProductCategoryRequest, opts ...grpc.CallOption) (*ProductCategoryResponse, error)
	ListProductCategories(ctx context.Context, in *ListProductCategoriesRequest, opts ...grpc.CallOption) (*ListProductCategoriesResponse, error)
	UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryRequest, opts ...grpc.CallOption) (*ProductCategoryResponse, error)
	DeleteProductCategory(ctx context.Context, in *DeleteProductCategoryRequest, opts ...grpc.CallOption) (*DeleteProductCategoryResponse, error)
	UploadCatalogImages(ctx context.Context, in *UploadCatalogImagesRequest, opts ...grpc.CallOption) (*CatalogImagesResponse, error)
	GetCatalogImage(ctx context.Context, in *GetCatalogImageRequest, opts ...grpc.CallOption) (*CatalogImageContentResponse, error)
	SetPrimaryCatalogImage(ctx context.Context, in *SetPrimaryCatalogImageRequest, opts ...grpc.CallOption) (*CatalogImagesResponse, error)
	DeleteCatalogImage(ctx context.Context, in *DeleteCatalogImageRequest, opts ...grpc.CallOption) (*DeleteCatalogImageResponse, error)
	CreateCatalogDiscount(ctx context.Context, in *CreateCatalogDiscountRequest, opts ...grpc.CallOption) (*CatalogDiscountResponse, error)
	ListCatalogDiscounts(ctx context.Context, in *ListCatalogDiscountsRequest, opts ...grpc.CallOption) (*ListCatalogDiscountsResponse, error)
	UpdateCatalogDiscount(ctx context.Context, in *UpdateCatalogDiscountRequest, opts ...grpc.CallOption) (*CatalogDiscountResponse, error)
	DeleteCatalogDiscount(ctx context.Context, in *DeleteCatalogDiscountRequest, opts ...grpc.CallOption) (*DeleteCatalogDiscountResponse, error)
	AssignServiceToCustomer(ctx context.Context, in *AssignServiceToCustomerRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error)
	GetCustomerService(ctx context.Context, in *GetCustomerServiceRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error)
	ListCustomerServices(ctx context.Context, in *ListCustomerServicesRequest, opts ...grpc.CallOption) (*ListCustomerServicesResponse, error)
	UpdateCustomerService(ctx context.Context, in *UpdateCustomerServiceRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error)
	RemoveServiceFromCustomer(ctx context.Context, in *RemoveServiceFromCustomerRequest, opts ...grpc.CallOption) (*RemoveServiceFromCustomerResponse, error)
	GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	AddCartItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error)
	UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error)
	RemoveCartItem(ctx context.Context, in *RemoveCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error)
	ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
}

type serviceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceManagerClient(cc grpc.ClientConnInterface) ServiceManagerClient {
	return &serviceManagerClient{cc}
}

func (c *serviceManagerClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	out := new(DeleteServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/DeleteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/DeleteProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) BatchUpsertProducts(ctx context.Context, in *BatchUpsertProductsRequest, opts ...grpc.CallOption) (*BatchUpsertProductsResponse, error) {
	out := new(BatchUpsertProductsResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/BatchUpsertProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) CreateProductCategory(ctx context.Context, in *CreateProductCategoryRequest, opts ...grpc.CallOption) (*ProductCategoryResponse, error) {
	out := new(ProductCategoryResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/CreateProductCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ListProductCategories(ctx context.Context, in *ListProductCategoriesRequest, opts ...grpc.CallOption) (*ListProductCategoriesResponse, error) {
	out := new(ListProductCategoriesResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ListProductCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateProductCategory(ctx context.Context, in *UpdateProductCategoryRequest, opts ...grpc.CallOption) (*ProductCategoryResponse, error) {
	out := new(ProductCategoryResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateProductCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) DeleteProductCategory(ctx context.Context, in *DeleteProductCategoryRequest, opts ...grpc.CallOption) (*DeleteProductCategoryResponse, error) {
	out := new(DeleteProductCategoryResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/DeleteProductCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UploadCatalogImages(ctx context.Context, in *UploadCatalogImagesRequest, opts ...grpc.CallOption) (*CatalogImagesResponse, error) {
	out := new(CatalogImagesResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UploadCatalogImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) GetCatalogImage(ctx context.Context, in *GetCatalogImageRequest, opts ...grpc.CallOption) (*CatalogImageContentResponse, error) {
	out := new(CatalogImageContentResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/GetCatalogImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) SetPrimaryCatalogImage(ctx context.Context, in *SetPrimaryCatalogImageRequest, opts ...grpc.CallOption) (*CatalogImagesResponse, error) {
	out := new(CatalogImagesResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/SetPrimaryCatalogImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) DeleteCatalogImage(ctx context.Context, in *DeleteCatalogImageRequest, opts ...grpc.CallOption) (*DeleteCatalogImageResponse, error) {
	out := new(DeleteCatalogImageResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/DeleteCatalogImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) CreateCatalogDiscount(ctx context.Context, in *CreateCatalogDiscountRequest, opts ...grpc.CallOption) (*CatalogDiscountResponse, error) {
	out := new(CatalogDiscountResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/CreateCatalogDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ListCatalogDiscounts(ctx context.Context, in *ListCatalogDiscountsRequest, opts ...grpc.CallOption) (*ListCatalogDiscountsResponse, error) {
	out := new(ListCatalogDiscountsResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ListCatalogDiscounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateCatalogDiscount(ctx context.Context, in *UpdateCatalogDiscountRequest, opts ...grpc.CallOption) (*CatalogDiscountResponse, error) {
	out := new(CatalogDiscountResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateCatalogDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) DeleteCatalogDiscount(ctx context.Context, in *DeleteCatalogDiscountRequest, opts ...grpc.CallOption) (*DeleteCatalogDiscountResponse, error) {
	out := new(DeleteCatalogDiscountResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/DeleteCatalogDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) AssignServiceToCustomer(ctx context.Context, in *AssignServiceToCustomerRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error) {
	out := new(CustomerServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/AssignServiceToCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) GetCustomerService(ctx context.Context, in *GetCustomerServiceRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error) {
	out := new(CustomerServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/GetCustomerService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ListCustomerServices(ctx context.Context, in *ListCustomerServicesRequest, opts ...grpc.CallOption) (*ListCustomerServicesResponse, error) {
	out := new(ListCustomerServicesResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ListCustomerServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateCustomerService(ctx context.Context, in *UpdateCustomerServiceRequest, opts ...grpc.CallOption) (*CustomerServiceResponse, error) {
	out := new(CustomerServiceResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateCustomerService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) RemoveServiceFromCustomer(ctx context.Context, in *RemoveServiceFromCustomerRequest, opts ...grpc.CallOption) (*RemoveServiceFromCustomerResponse, error) {
	out := new(RemoveServiceFromCustomerResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/RemoveServiceFromCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) GetCart(ctx context.Context, in *GetCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/GetCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) AddCartItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/AddCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/UpdateCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) RemoveCartItem(ctx context.Context, in *RemoveCartItemRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/RemoveCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, "/service.ServiceManager/ClearCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceManagerServer is the server API for ServiceManager service.
// All implementations must embed UnimplementedServiceManagerServer
// for forward compatibility
type ServiceManagerServer interface {
	CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error)
	GetService(context.Context, *GetServiceRequest) (*ServiceResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error)
	DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*ProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*ProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	BatchUpsertProducts(context.Context, *BatchUpsertProductsRequest) (*BatchUpsertProductsResponse, error)
	CreateProductCategory(context.Context, *CreateProductCategoryRequest) (*ProductCategoryResponse, error)
	ListProductCategories(context.Context, *ListProductCategoriesRequest) (*ListProductCategoriesResponse, error)
	UpdateProductCategory(context.Context, *UpdateProductCategoryRequest) (*ProductCategoryResponse, error)
	DeleteProductCategory(context.Context, *DeleteProductCategoryRequest) (*DeleteProductCategoryResponse, error)
	UploadCatalogImages(context.Context, *UploadCatalogImagesRequest) (*CatalogImagesResponse, error)
	GetCatalogImage(context.Context, *GetCatalogImageRequest) (*CatalogImageContentResponse, error)
	SetPrimaryCatalogImage(context.Context, *SetPrimaryCatalogImageRequest) (*CatalogImagesResponse, error)
	DeleteCatalogImage(context.Context, *DeleteCatalogImageRequest) (*DeleteCatalogImageResponse, error)
	CreateCatalogDiscount(context.Context, *CreateCatalogDiscountRequest) (*CatalogDiscountResponse, error)
	ListCatalogDiscounts(context.Context, *ListCatalogDiscountsRequest) (*ListCatalogDiscountsResponse, error)
	UpdateCatalogDiscount(context.Context, *UpdateCatalogDiscountRequest) (*CatalogDiscountResponse, error)
	DeleteCatalogDiscount(context.Context, *DeleteCatalogDiscountRequest) (*DeleteCatalogDiscountResponse, error)
	AssignServiceToCustomer(context.Context, *AssignServiceToCustomerRequest) (*CustomerServiceResponse, error)
	GetCustomerService(context.Context, *GetCustomerServiceRequest) (*CustomerServiceResponse, error)
	ListCustomerServices(context.Context, *ListCustomerServicesRequest) (*ListCustomerServicesResponse, error)
	UpdateCustomerService(context.Context, *UpdateCustomerServiceRequest) (*CustomerServiceResponse, error)
	RemoveServiceFromCustomer(context.Context, *RemoveServiceFromCustomerRequest) (*RemoveServiceFromCustomerResponse, error)
	GetCart(context.Context, *GetCartRequest) (*CartResponse, error)
	AddCartItem(context.Context, *AddCartItemRequest) (*CartResponse, error)
	UpdateCartItem(context.Context, *UpdateCartItemRequest) (*CartResponse, error)
	RemoveCartItem(context.Context, *RemoveCartItemRequest) (*CartResponse, error)
	ClearCart(context.Context, *ClearCartRequest) (*CartResponse, error)
	mustEmbedUnimplementedServiceManagerServer()
}

// UnimplementedServiceManagerServer must be embedded to have forward compatible implementations.
type UnimplementedServiceManagerServer struct {
}

func (UnimplementedServiceManagerServer) CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedServiceManagerServer) GetService(context.Context, *GetServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedServiceManagerServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedServiceManagerServer) UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedServiceManagerServer) DeleteService(context.Context, *DeleteServiceRequest) (*DeleteServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedServiceManagerServer) CreateProduct(context.Context, *CreateProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedServiceManagerServer) GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedServiceManagerServer) ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedServiceManagerServer) UpdateProduct(context.Context, *UpdateProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedServiceManagerServer) DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedServiceManagerServer) BatchUpsertProducts(context.Context, *BatchUpsertProductsRequest) (*BatchUpsertProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpsertProducts not implemented")
}
func (UnimplementedServiceManagerServer) CreateProductCategory(context.Context, *CreateProductCategoryRequest) (*ProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductCategory not implemented")
}
func (UnimplementedServiceManagerServer) ListProductCategories(context.Context, *ListProductCategoriesRequest) (*ListProductCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProductCategories not implemented")
}
func (UnimplementedServiceManagerServer) UpdateProductCategory(context.Context, *UpdateProductCategoryRequest) (*ProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductCategory not implemented")
}
func (UnimplementedServiceManagerServer) DeleteProductCategory(context.Context, *DeleteProductCategoryRequest) (*DeleteProductCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductCategory not implemented")
}
func (UnimplementedServiceManagerServer) UploadCatalogImages(context.Context, *UploadCatalogImagesRequest) (*CatalogImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadCatalogImages not implemented")
}
func (UnimplementedServiceManagerServer) GetCatalogImage(context.Context, *GetCatalogImageRequest) (*CatalogImageContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalogImage not implemented")
}
func (UnimplementedServiceManagerServer) SetPrimaryCatalogImage(context.Context, *SetPrimaryCatalogImageRequest) (*CatalogImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimaryCatalogImage not implemented")
}
func (UnimplementedServiceManagerServer) DeleteCatalogImage(context.Context, *DeleteCatalogImageRequest) (*DeleteCatalogImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCatalogImage not implemented")
}
func (UnimplementedServiceManagerServer) CreateCatalogDiscount(context.Context, *CreateCatalogDiscountRequest) (*CatalogDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCatalogDiscount not implemented")
}
func (UnimplementedServiceManagerServer) ListCatalogDiscounts(context.Context, *ListCatalogDiscountsRequest) (*ListCatalogDiscountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalogDiscounts not implemented")
}
func (UnimplementedServiceManagerServer) UpdateCatalogDiscount(context.Context, *UpdateCatalogDiscountRequest) (*CatalogDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCatalogDiscount not implemented")
}
func (UnimplementedServiceManagerServer) DeleteCatalogDiscount(context.Context, *DeleteCatalogDiscountRequest) (*DeleteCatalogDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCatalogDiscount not implemented")
}
func (UnimplementedServiceManagerServer) AssignServiceToCustomer(context.Context, *AssignServiceToCustomerRequest) (*CustomerServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignServiceToCustomer not implemented")
}
func (UnimplementedServiceManagerServer) GetCustomerService(context.Context, *GetCustomerServiceRequest) (*CustomerServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomerService not implemented")
}
func (UnimplementedServiceManagerServer) ListCustomerServices(context.Context, *ListCustomerServicesRequest) (*ListCustomerServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCustomerServices not implemented")
}
func (UnimplementedServiceManagerServer) UpdateCustomerService(context.Context, *UpdateCustomerServiceRequest) (*CustomerServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomerService not implemented")
}
func (UnimplementedServiceManagerServer) RemoveServiceFromCustomer(context.Context, *RemoveServiceFromCustomerRequest) (*RemoveServiceFromCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveServiceFromCustomer not implemented")
}
func (UnimplementedServiceManagerServer) GetCart(context.Context, *GetCartRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCart not implemented")
}
func (UnimplementedServiceManagerServer) AddCartItem(context.Context, *AddCartItemRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCartItem not implemented")
}
func (UnimplementedServiceManagerServer) UpdateCartItem(context.Context, *UpdateCartItemRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartItem not implemented")
}
func (UnimplementedServiceManagerServer) RemoveCartItem(context.Context, *RemoveCartItemRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCartItem not implemented")
}
func (UnimplementedServiceManagerServer) ClearCart(context.Context, *ClearCartRequest) (*CartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearCart not implemented")
}
func (UnimplementedServiceManagerServer) mustEmbedUnimplementedServiceManagerServer() {}

// UnsafeServiceManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceManagerServer will
// result in compilation errors.
type UnsafeServiceManagerServer interface {
	mustEmbedUnimplementedServiceManagerServer()
}

func RegisterServiceManagerServer(s grpc.ServiceRegistrar, srv ServiceManagerServer) {
	s.RegisterService(&ServiceManager_ServiceDesc, srv)
}

func _ServiceManager_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).DeleteService(ctx, req.(*DeleteServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_BatchUpsertProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).BatchUpsertProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/BatchUpsertProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).BatchUpsertProducts(ctx, req.(*BatchUpsertProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_CreateProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).CreateProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/CreateProductCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).CreateProductCategory(ctx, req.(*CreateProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ListProductCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ListProductCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ListProductCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ListProductCategories(ctx, req.(*ListProductCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateProductCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateProductCategory(ctx, req.(*UpdateProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_DeleteProductCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).DeleteProductCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/DeleteProductCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).DeleteProductCategory(ctx, req.(*DeleteProductCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UploadCatalogImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCatalogImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UploadCatalogImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UploadCatalogImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UploadCatalogImages(ctx, req.(*UploadCatalogImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_GetCatalogImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).GetCatalogImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/GetCatalogImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).GetCatalogImage(ctx, req.(*GetCatalogImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_SetPrimaryCatalogImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryCatalogImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).SetPrimaryCatalogImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/SetPrimaryCatalogImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).SetPrimaryCatalogImage(ctx, req.(*SetPrimaryCatalogImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_DeleteCatalogImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCatalogImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).DeleteCatalogImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/DeleteCatalogImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).DeleteCatalogImage(ctx, req.(*DeleteCatalogImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_CreateCatalogDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCatalogDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).CreateCatalogDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/CreateCatalogDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).CreateCatalogDiscount(ctx, req.(*CreateCatalogDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ListCatalogDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ListCatalogDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ListCatalogDiscounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ListCatalogDiscounts(ctx, req.(*ListCatalogDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateCatalogDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatalogDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateCatalogDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateCatalogDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateCatalogDiscount(ctx, req.(*UpdateCatalogDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_DeleteCatalogDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCatalogDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).DeleteCatalogDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/DeleteCatalogDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).DeleteCatalogDiscount(ctx, req.(*DeleteCatalogDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_AssignServiceToCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignServiceToCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).AssignServiceToCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/AssignServiceToCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).AssignServiceToCustomer(ctx, req.(*AssignServiceToCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_GetCustomerService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).GetCustomerService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/GetCustomerService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).GetCustomerService(ctx, req.(*GetCustomerServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ListCustomerServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ListCustomerServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ListCustomerServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ListCustomerServices(ctx, req.(*ListCustomerServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateCustomerService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCustomerServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateCustomerService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateCustomerService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateCustomerService(ctx, req.(*UpdateCustomerServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_RemoveServiceFromCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServiceFromCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).RemoveServiceFromCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/RemoveServiceFromCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).RemoveServiceFromCustomer(ctx, req.(*RemoveServiceFromCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_GetCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).GetCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/GetCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).GetCart(ctx, req.(*GetCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_AddCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).AddCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/AddCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).AddCartItem(ctx, req.(*AddCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_UpdateCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).UpdateCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/UpdateCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).UpdateCartItem(ctx, req.(*UpdateCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_RemoveCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).RemoveCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/RemoveCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).RemoveCartItem(ctx, req.(*RemoveCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_ClearCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).ClearCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.ServiceManager/ClearCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).ClearCart(ctx, req.(*ClearCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceManager_ServiceDesc is the grpc.ServiceDesc for ServiceManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ServiceManager",
	HandlerType: (*ServiceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _ServiceManager_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ServiceManager_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ServiceManager_ListServices_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _ServiceManager_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ServiceManager_DeleteService_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _ServiceManager_CreateProduct_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ServiceManager_GetProduct_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _ServiceManager_ListProducts_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _ServiceManager_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _ServiceManager_DeleteProduct_Handler,
		},
		{
			MethodName: "BatchUpsertProducts",
			Handler:    _ServiceManager_BatchUpsertProducts_Handler,
		},
		{
			MethodName: "CreateProductCategory",
			Handler:    _ServiceManager_CreateProductCategory_Handler,
		},
		{
			MethodName: "ListProductCategories",
			Handler:    _ServiceManager_ListProductCategories_Handler,
		},
		{
			MethodName: "UpdateProductCategory",
			Handler:    _ServiceManager_UpdateProductCategory_Handler,
		},
		{
			MethodName: "DeleteProductCategory",
			Handler:    _ServiceManager_DeleteProductCategory_Handler,
		},
		{
			MethodName: "UploadCatalogImages",
			Handler:    _ServiceManager_UploadCatalogImages_Handler,
		},
		{
			MethodName: "GetCatalogImage",
			Handler:    _ServiceManager_GetCatalogImage_Handler,
		},
		{
			MethodName: "SetPrimaryCatalogImage",
			Handler:    _ServiceManager_SetPrimaryCatalogImage_Handler,
		},
		{
			MethodName: "DeleteCatalogImage",
			Handler:    _ServiceManager_DeleteCatalogImage_Handler,
		},
		{
			MethodName: "CreateCatalogDiscount",
			Handler:    _ServiceManager_CreateCatalogDiscount_Handler,
		},
		{
			MethodName: "ListCatalogDiscounts",
			Handler:    _ServiceManager_ListCatalogDiscounts_Handler,
		},
		{
			MethodName: "UpdateCatalogDiscount",
			Handler:    _ServiceManager_UpdateCatalogDiscount_Handler,
		},
		{
			MethodName: "DeleteCatalogDiscount",
			Handler:    _ServiceManager_DeleteCatalogDiscount_Handler,
		},
		{
			MethodName: "AssignServiceToCustomer",
			Handler:    _ServiceManager_AssignServiceToCustomer_Handler,
		},
		{
			MethodName: "GetCustomerService",
			Handler:    _ServiceManager_GetCustomerService_Handler,
		},
		{
			MethodName: "ListCustomerServices",
			Handler:    _ServiceManager_ListCustomerServices_Handler,
		},
		{
			MethodName: "UpdateCustomerService",
			Handler:    _ServiceManager_UpdateCustomerService_Handler,
		},
		{
			MethodName: "RemoveServiceFromCustomer",
			Handler:    _ServiceManager_RemoveServiceFromCustomer_Handler,
		},
		{
			MethodName: "GetCart",
			Handler:    _ServiceManager_GetCart_Handler,
		},
		{
			MethodName: "AddCartItem",
			Handler:    _ServiceManager_AddCartItem_Handler,
		},
		{
			MethodName: "UpdateCartItem",
			Handler:    _ServiceManager_UpdateCartItem_Handler,
		},
		{
			MethodName: "RemoveCartItem",
			Handler:    _ServiceManager_RemoveCartItem_Handler,
		},
		{
			MethodName: "ClearCart",
			Handler:    _ServiceManager_ClearCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service/service.proto",
}
