// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: proto/career/career.proto

package career

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CareerProfileServiceClient is the client API for CareerProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CareerProfileServiceClient interface {
	CreateSkillProfile(ctx context.Context, in *CreateSkillProfileRequest, opts ...grpc.CallOption) (*SkillProfileResponse, error)
	ListMySkillProfiles(ctx context.Context, in *ListMySkillProfilesRequest, opts ...grpc.CallOption) (*ListSkillProfilesResponse, error)
	AddSkillToProfile(ctx context.Context, in *AddSkillToProfileRequest, opts ...grpc.CallOption) (*SkillProfileResponse, error)
	CreateResume(ctx context.Context, in *CreateResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error)
	ListMyResumes(ctx context.Context, in *ListMyResumesRequest, opts ...grpc.CallOption) (*ListResumesResponse, error)
	DownloadResume(ctx context.Context, in *DownloadResumeRequest, opts ...grpc.CallOption) (*DownloadResumeResponse, error)
}

type careerProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCareerProfileServiceClient(cc grpc.ClientConnInterface) CareerProfileServiceClient {
	return &careerProfileServiceClient{cc}
}

func (c *careerProfileServiceClient) CreateSkillProfile(ctx context.Context, in *CreateSkillProfileRequest, opts ...grpc.CallOption) (*SkillProfileResponse, error) {
	out := new(SkillProfileResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/CreateSkillProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *careerProfileServiceClient) ListMySkillProfiles(ctx context.Context, in *ListMySkillProfilesRequest, opts ...grpc.CallOption) (*ListSkillProfilesResponse, error) {
	out := new(ListSkillProfilesResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/ListMySkillProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *careerProfileServiceClient) AddSkillToProfile(ctx context.Context, in *AddSkillToProfileRequest, opts ...grpc.CallOption) (*SkillProfileResponse, error) {
	out := new(SkillProfileResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/AddSkillToProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *careerProfileServiceClient) CreateResume(ctx context.Context, in *CreateResumeRequest, opts ...grpc.CallOption) (*ResumeResponse, error) {
	out := new(ResumeResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/CreateResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *careerProfileServiceClient) ListMyResumes(ctx context.Context, in *ListMyResumesRequest, opts ...grpc.CallOption) (*ListResumesResponse, error) {
	out := new(ListResumesResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/ListMyResumes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *careerProfileServiceClient) DownloadResume(ctx context.Context, in *DownloadResumeRequest, opts ...grpc.CallOption) (*DownloadResumeResponse, error) {
	out := new(DownloadResumeResponse)
	err := c.cc.Invoke(ctx, "/career.CareerProfileService/DownloadResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CareerProfileServiceServer is the server API for CareerProfileService service.
// All implementations must embed UnimplementedCareerProfileServiceServer
// for forward compatibility
type CareerProfileServiceServer interface {
	CreateSkillProfile(context.Context, *CreateSkillProfileRequest) (*SkillProfileResponse, error)
	ListMySkillProfiles(context.Context, *ListMySkillProfilesRequest) (*ListSkillProfilesResponse, error)
	AddSkillToProfile(context.Context, *AddSkillToProfileRequest) (*SkillProfileResponse, error)
	CreateResume(context.Context, *CreateResumeRequest) (*ResumeResponse, error)
	ListMyResumes(context.Context, *ListMyResumesRequest) (*ListResumesResponse, error)
	DownloadResume(context.Context, *DownloadResumeRequest) (*DownloadResumeResponse, error)
	mustEmbedUnimplementedCareerProfileServiceServer()
}

// UnimplementedCareerProfileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCareerProfileServiceServer struct {
}

func (UnimplementedCareerProfileServiceServer) CreateSkillProfile(context.Context, *CreateSkillProfileRequest) (*SkillProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSkillProfile not implemented")
}
func (UnimplementedCareerProfileServiceServer) ListMySkillProfiles(context.Context, *ListMySkillProfilesRequest) (*ListSkillProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMySkillProfiles not implemented")
}
func (UnimplementedCareerProfileServiceServer) AddSkillToProfile(context.Context, *AddSkillToProfileRequest) (*SkillProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSkillToProfile not implemented")
}
func (UnimplementedCareerProfileServiceServer) CreateResume(context.Context, *CreateResumeRequest) (*ResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResume not implemented")
}
func (UnimplementedCareerProfileServiceServer) ListMyResumes(context.Context, *ListMyResumesRequest) (*ListResumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyResumes not implemented")
}
func (UnimplementedCareerProfileServiceServer) DownloadResume(context.Context, *DownloadResumeRequest) (*DownloadResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadResume not implemented")
}
func (UnimplementedCareerProfileServiceServer) mustEmbedUnimplementedCareerProfileServiceServer() {}

// UnsafeCareerProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CareerProfileServiceServer will
// result in compilation errors.
type UnsafeCareerProfileServiceServer interface {
	mustEmbedUnimplementedCareerProfileServiceServer()
}

func RegisterCareerProfileServiceServer(s grpc.ServiceRegistrar, srv CareerProfileServiceServer) {
	s.RegisterService(&CareerProfileService_ServiceDesc, srv)
}

func _CareerProfileService_CreateSkillProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).CreateSkillProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/CreateSkillProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).CreateSkillProfile(ctx, req.(*CreateSkillProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CareerProfileService_ListMySkillProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMySkillProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).ListMySkillProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/ListMySkillProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).ListMySkillProfiles(ctx, req.(*ListMySkillProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CareerProfileService_AddSkillToProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillToProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).AddSkillToProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/AddSkillToProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).AddSkillToProfile(ctx, req.(*AddSkillToProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CareerProfileService_CreateResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).CreateResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/CreateResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).CreateResume(ctx, req.(*CreateResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CareerProfileService_ListMyResumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyResumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).ListMyResumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/ListMyResumes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).ListMyResumes(ctx, req.(*ListMyResumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CareerProfileService_DownloadResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CareerProfileServiceServer).DownloadResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.CareerProfileService/DownloadResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CareerProfileServiceServer).DownloadResume(ctx, req.(*DownloadResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CareerProfileService_ServiceDesc is the grpc.ServiceDesc for CareerProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CareerProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "career.CareerProfileService",
	HandlerType: (*CareerProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSkillProfile",
			Handler:    _CareerProfileService_CreateSkillProfile_Handler,
		},
		{
			MethodName: "ListMySkillProfiles",
			Handler:    _CareerProfileService_ListMySkillProfiles_Handler,
		},
		{
			MethodName: "AddSkillToProfile",
			Handler:    _CareerProfileService_AddSkillToProfile_Handler,
		},
		{
			MethodName: "CreateResume",
			Handler:    _CareerProfileService_CreateResume_Handler,
		},
		{
			MethodName: "ListMyResumes",
			Handler:    _CareerProfileService_ListMyResumes_Handler,
		},
		{
			MethodName: "DownloadResume",
			Handler:    _CareerProfileService_DownloadResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/career/career.proto",
}

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
	ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesResponse, error)
	GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
	UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error)
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	CloseJob(ctx context.Context, in *CloseJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	ReopenJob(ctx context.Context, in *ReopenJobRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/CreateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ListCompanies(ctx context.Context, in *ListCompaniesRequest, opts ...grpc.CallOption) (*ListCompaniesResponse, error) {
	out := new(ListCompaniesResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/ListCompanies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetCompany(ctx context.Context, in *GetCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/GetCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateCompany(ctx context.Context, in *UpdateCompanyRequest, opts ...grpc.CallOption) (*CompanyResponse, error) {
	out := new(CompanyResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/UpdateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/CreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/SearchJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) UpdateJob(ctx context.Context, in *UpdateJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) CloseJob(ctx context.Context, in *CloseJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/CloseJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ReopenJob(ctx context.Context, in *ReopenJobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/career.JobService/ReopenJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility
type JobServiceServer interface {
	CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyResponse, error)
	ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesResponse, error)
	GetCompany(context.Context, *GetCompanyRequest) (*CompanyResponse, error)
	UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyResponse, error)
	CreateJob(context.Context, *CreateJobRequest) (*JobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*JobResponse, error)
	SearchJobs(context.Context, *SearchJobsRequest) (*ListJobsResponse, error)
	UpdateJob(context.Context, *UpdateJobRequest) (*JobResponse, error)
	CloseJob(context.Context, *CloseJobRequest) (*JobResponse, error)
	ReopenJob(context.Context, *ReopenJobRequest) (*JobResponse, error)
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (UnimplementedJobServiceServer) CreateCompany(context.Context, *CreateCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}
func (UnimplementedJobServiceServer) ListCompanies(context.Context, *ListCompaniesRequest) (*ListCompaniesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCompanies not implemented")
}
func (UnimplementedJobServiceServer) GetCompany(context.Context, *GetCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompany not implemented")
}
func (UnimplementedJobServiceServer) UpdateCompany(context.Context, *UpdateCompanyRequest) (*CompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompany not implemented")
}
func (UnimplementedJobServiceServer) CreateJob(context.Context, *CreateJobRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedJobServiceServer) GetJob(context.Context, *GetJobRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobServiceServer) SearchJobs(context.Context, *SearchJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchJobs not implemented")
}
func (UnimplementedJobServiceServer) UpdateJob(context.Context, *UpdateJobRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedJobServiceServer) CloseJob(context.Context, *CloseJobRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseJob not implemented")
}
func (UnimplementedJobServiceServer) ReopenJob(context.Context, *ReopenJobRequest) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReopenJob not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ListCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ListCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/ListCompanies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ListCompanies(ctx, req.(*ListCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/GetCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetCompany(ctx, req.(*GetCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/UpdateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateCompany(ctx, req.(*UpdateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/CreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SearchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SearchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/SearchJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SearchJobs(ctx, req.(*SearchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).UpdateJob(ctx, req.(*UpdateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_CloseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).CloseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/CloseJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).CloseJob(ctx, req.(*CloseJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ReopenJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReopenJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ReopenJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobService/ReopenJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ReopenJob(ctx, req.(*ReopenJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "career.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompany",
			Handler:    _JobService_CreateCompany_Handler,
		},
		{
			MethodName: "ListCompanies",
			Handler:    _JobService_ListCompanies_Handler,
		},
		{
			MethodName: "GetCompany",
			Handler:    _JobService_GetCompany_Handler,
		},
		{
			MethodName: "UpdateCompany",
			Handler:    _JobService_UpdateCompany_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _JobService_CreateJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobService_GetJob_Handler,
		},
		{
			MethodName: "SearchJobs",
			Handler:    _JobService_SearchJobs_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _JobService_UpdateJob_Handler,
		},
		{
			MethodName: "CloseJob",
			Handler:    _JobService_CloseJob_Handler,
		},
		{
			MethodName: "ReopenJob",
			Handler:    _JobService_ReopenJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/career/career.proto",
}

// JobCartServiceClient is the client API for JobCartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobCartServiceClient interface {
	GetJobCart(ctx context.Context, in *GetJobCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error)
	AddJobToCart(ctx context.Context, in *AddJobToCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error)
	UpdateCartItemProfile(ctx context.Context, in *UpdateCartItemProfileRequest, opts ...grpc.CallOption) (*JobCartResponse, error)
	RemoveJobFromCart(ctx context.Context, in *RemoveJobFromCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error)
	ClearJobCart(ctx context.Context, in *ClearJobCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error)
}

type jobCartServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobCartServiceClient(cc grpc.ClientConnInterface) JobCartServiceClient {
	return &jobCartServiceClient{cc}
}

func (c *jobCartServiceClient) GetJobCart(ctx context.Context, in *GetJobCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error) {
	out := new(JobCartResponse)
	err := c.cc.Invoke(ctx, "/career.JobCartService/GetJobCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobCartServiceClient) AddJobToCart(ctx context.Context, in *AddJobToCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error) {
	out := new(JobCartResponse)
	err := c.cc.Invoke(ctx, "/career.JobCartService/AddJobToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobCartServiceClient) UpdateCartItemProfile(ctx context.Context, in *UpdateCartItemProfileRequest, opts ...grpc.CallOption) (*JobCartResponse, error) {
	out := new(JobCartResponse)
	err := c.cc.Invoke(ctx, "/career.JobCartService/UpdateCartItemProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobCartServiceClient) RemoveJobFromCart(ctx context.Context, in *RemoveJobFromCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error) {
	out := new(JobCartResponse)
	err := c.cc.Invoke(ctx, "/career.JobCartService/RemoveJobFromCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobCartServiceClient) ClearJobCart(ctx context.Context, in *ClearJobCartRequest, opts ...grpc.CallOption) (*JobCartResponse, error) {
	out := new(JobCartResponse)
	err := c.cc.Invoke(ctx, "/career.JobCartService/ClearJobCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobCartServiceServer is the server API for JobCartService service.
// All implementations must embed UnimplementedJobCartServiceServer
// for forward compatibility
type JobCartServiceServer interface {
	GetJobCart(context.Context, *GetJobCartRequest) (*JobCartResponse, error)
	AddJobToCart(context.Context, *AddJobToCartRequest) (*JobCartResponse, error)
	UpdateCartItemProfile(context.Context, *UpdateCartItemProfileRequest) (*JobCartResponse, error)
	RemoveJobFromCart(context.Context, *RemoveJobFromCartRequest) (*JobCartResponse, error)
	ClearJobCart(context.Context, *ClearJobCartRequest) (*JobCartResponse, error)
	mustEmbedUnimplementedJobCartServiceServer()
}

// UnimplementedJobCartServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobCartServiceServer struct {
}

func (UnimplementedJobCartServiceServer) GetJobCart(context.Context, *GetJobCartRequest) (*JobCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobCart not implemented")
}
func (UnimplementedJobCartServiceServer) AddJobToCart(context.Context, *AddJobToCartRequest) (*JobCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJobToCart not implemented")
}
func (UnimplementedJobCartServiceServer) UpdateCartItemProfile(context.Context, *UpdateCartItemProfileRequest) (*JobCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartItemProfile not implemented")
}
func (UnimplementedJobCartServiceServer) RemoveJobFromCart(context.Context, *RemoveJobFromCartRequest) (*JobCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveJobFromCart not implemented")
}
func (UnimplementedJobCartServiceServer) ClearJobCart(context.Context, *ClearJobCartRequest) (*JobCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearJobCart not implemented")
}
func (UnimplementedJobCartServiceServer) mustEmbedUnimplementedJobCartServiceServer() {}

// UnsafeJobCartServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobCartServiceServer will
// result in compilation errors.
type UnsafeJobCartServiceServer interface {
	mustEmbedUnimplementedJobCartServiceServer()
}

func RegisterJobCartServiceServer(s grpc.ServiceRegistrar, srv JobCartServiceServer) {
	s.RegisterService(&JobCartService_ServiceDesc, srv)
}

func _JobCartService_GetJobCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobCartServiceServer).GetJobCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobCartService/GetJobCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobCartServiceServer).GetJobCart(ctx, req.(*GetJobCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobCartService_AddJobToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobCartServiceServer).AddJobToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobCartService/AddJobToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobCartServiceServer).AddJobToCart(ctx, req.(*AddJobToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobCartService_UpdateCartItemProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartItemProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobCartServiceServer).UpdateCartItemProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobCartService/UpdateCartItemProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobCartServiceServer).UpdateCartItemProfile(ctx, req.(*UpdateCartItemProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobCartService_RemoveJobFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJobFromCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobCartServiceServer).RemoveJobFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobCartService/RemoveJobFromCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobCartServiceServer).RemoveJobFromCart(ctx, req.(*RemoveJobFromCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobCartService_ClearJobCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearJobCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobCartServiceServer).ClearJobCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobCartService/ClearJobCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobCartServiceServer).ClearJobCart(ctx, req.(*ClearJobCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobCartService_ServiceDesc is the grpc.ServiceDesc for JobCartService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobCartService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "career.JobCartService",
	HandlerType: (*JobCartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobCart",
			Handler:    _JobCartService_GetJobCart_Handler,
		},
		{
			MethodName: "AddJobToCart",
			Handler:    _JobCartService_AddJobToCart_Handler,
		},
		{
			MethodName: "UpdateCartItemProfile",
			Handler:    _JobCartService_UpdateCartItemProfile_Handler,
		},
		{
			MethodName: "RemoveJobFromCart",
			Handler:    _JobCartService_RemoveJobFromCart_Handler,
		},
		{
			MethodName: "ClearJobCart",
			Handler:    _JobCartService_ClearJobCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/career/career.proto",
}

// JobApplicationServiceClient is the client API for JobApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobApplicationServiceClient interface {
	ApplyToJob(ctx context.Context, in *ApplyToJobRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error)
	ApplyToCartJobs(ctx context.Context, in *ApplyToCartJobsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error)
	ListMyApplications(ctx context.Context, in *ListMyApplicationsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error)
	GetMyApplication(ctx context.Context, in *GetMyApplicationRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error)
	ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error)
	UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error)
}

type jobApplicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobApplicationServiceClient(cc grpc.ClientConnInterface) JobApplicationServiceClient {
	return &jobApplicationServiceClient{cc}
}

func (c *jobApplicationServiceClient) ApplyToJob(ctx context.Context, in *ApplyToJobRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error) {
	out := new(JobApplicationResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/ApplyToJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) ApplyToCartJobs(ctx context.Context, in *ApplyToCartJobsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error) {
	out := new(ListJobApplicationsResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/ApplyToCartJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) ListMyApplications(ctx context.Context, in *ListMyApplicationsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error) {
	out := new(ListJobApplicationsResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/ListMyApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) GetMyApplication(ctx context.Context, in *GetMyApplicationRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error) {
	out := new(JobApplicationResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/GetMyApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...grpc.CallOption) (*ListJobApplicationsResponse, error) {
	out := new(ListJobApplicationsResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/ListApplications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error) {
	out := new(JobApplicationResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/GetApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobApplicationServiceClient) UpdateApplicationStatus(ctx context.Context, in *UpdateApplicationStatusRequest, opts ...grpc.CallOption) (*JobApplicationResponse, error) {
	out := new(JobApplicationResponse)
	err := c.cc.Invoke(ctx, "/career.JobApplicationService/UpdateApplicationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobApplicationServiceServer is the server API for JobApplicationService service.
// All implementations must embed UnimplementedJobApplicationServiceServer
// for forward compatibility
type JobApplicationServiceServer interface {
	ApplyToJob(context.Context, *ApplyToJobRequest) (*JobApplicationResponse, error)
	ApplyToCartJobs(context.Context, *ApplyToCartJobsRequest) (*ListJobApplicationsResponse, error)
	ListMyApplications(context.Context, *ListMyApplicationsRequest) (*ListJobApplicationsResponse, error)
	GetMyApplication(context.Context, *GetMyApplicationRequest) (*JobApplicationResponse, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListJobApplicationsResponse, error)
	GetApplication(context.Context, *GetApplicationRequest) (*JobApplicationResponse, error)
	UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*JobApplicationResponse, error)
	mustEmbedUnimplementedJobApplicationServiceServer()
}

// UnimplementedJobApplicationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobApplicationServiceServer struct {
}

func (UnimplementedJobApplicationServiceServer) ApplyToJob(context.Context, *ApplyToJobRequest) (*JobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyToJob not implemented")
}
func (UnimplementedJobApplicationServiceServer) ApplyToCartJobs(context.Context, *ApplyToCartJobsRequest) (*ListJobApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyToCartJobs not implemented")
}
func (UnimplementedJobApplicationServiceServer) ListMyApplications(context.Context, *ListMyApplicationsRequest) (*ListJobApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyApplications not implemented")
}
func (UnimplementedJobApplicationServiceServer) GetMyApplication(context.Context, *GetMyApplicationRequest) (*JobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) ListApplications(context.Context, *ListApplicationsRequest) (*ListJobApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedJobApplicationServiceServer) GetApplication(context.Context, *GetApplicationRequest) (*JobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplication not implemented")
}
func (UnimplementedJobApplicationServiceServer) UpdateApplicationStatus(context.Context, *UpdateApplicationStatusRequest) (*JobApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApplicationStatus not implemented")
}
func (UnimplementedJobApplicationServiceServer) mustEmbedUnimplementedJobApplicationServiceServer() {}

// UnsafeJobApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobApplicationServiceServer will
// result in compilation errors.
type UnsafeJobApplicationServiceServer interface {
	mustEmbedUnimplementedJobApplicationServiceServer()
}

func RegisterJobApplicationServiceServer(s grpc.ServiceRegistrar, srv JobApplicationServiceServer) {
	s.RegisterService(&JobApplicationService_ServiceDesc, srv)
}

func _JobApplicationService_ApplyToJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyToJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).ApplyToJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/ApplyToJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).ApplyToJob(ctx, req.(*ApplyToJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_ApplyToCartJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyToCartJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).ApplyToCartJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/ApplyToCartJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).ApplyToCartJobs(ctx, req.(*ApplyToCartJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_ListMyApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).ListMyApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/ListMyApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).ListMyApplications(ctx, req.(*ListMyApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_GetMyApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).GetMyApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/GetMyApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).GetMyApplication(ctx, req.(*GetMyApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/ListApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).ListApplications(ctx, req.(*ListApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/GetApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobApplicationService_UpdateApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobApplicationServiceServer).UpdateApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/career.JobApplicationService/UpdateApplicationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobApplicationServiceServer).UpdateApplicationStatus(ctx, req.(*UpdateApplicationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobApplicationService_ServiceDesc is the grpc.ServiceDesc for JobApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "career.JobApplicationService",
	HandlerType: (*JobApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyToJob",
			Handler:    _JobApplicationService_ApplyToJob_Handler,
		},
		{
			MethodName: "ApplyToCartJobs",
			Handler:    _JobApplicationService_ApplyToCartJobs_Handler,
		},
		{
			MethodName: "ListMyApplications",
			Handler:    _JobApplicationService_ListMyApplications_Handler,
		},
		{
			MethodName: "GetMyApplication",
			Handler:    _JobApplicationService_GetMyApplication_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _JobApplicationService_ListApplications_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _JobApplicationService_GetApplication_Handler,
		},
		{
			MethodName: "UpdateApplicationStatus",
			Handler:    _JobApplicationService_UpdateApplicationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/career/career.proto",
}
