// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/calendar/calendar.proto

package calendarpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId            string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Title                 string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	EventType             string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	StartsAt              *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Timezone              string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Location              string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	MeetingUrl            string                 `protobuf:"bytes,10,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	RelatedEntityType     string                 `protobuf:"bytes,11,opt,name=related_entity_type,json=relatedEntityType,proto3" json:"related_entity_type,omitempty"`
	RelatedEntityId       string                 `protobuf:"bytes,12,opt,name=related_entity_id,json=relatedEntityId,proto3" json:"related_entity_id,omitempty"`
	JobId                 string                 `protobuf:"bytes,13,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobTitle              string                 `protobuf:"bytes,14,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Company               string                 `protobuf:"bytes,15,opt,name=company,proto3" json:"company,omitempty"`
	ReminderMinutesBefore int32                  `protobuf:"varint,16,opt,name=reminder_minutes_before,json=reminderMinutesBefore,proto3" json:"reminder_minutes_before,omitempty"`
	Status                string                 `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CalendarEvent) Reset() {
	*x = CalendarEvent{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarEvent) ProtoMessage() {}

func (x *CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarEvent.ProtoReflect.Descriptor instead.
func (*CalendarEvent) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalendarEvent) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CalendarEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CalendarEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CalendarEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CalendarEvent) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CalendarEvent) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *CalendarEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CalendarEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CalendarEvent) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *CalendarEvent) GetRelatedEntityType() string {
	if x != nil {
		return x.RelatedEntityType
	}
	return ""
}

func (x *CalendarEvent) GetRelatedEntityId() string {
	if x != nil {
		return x.RelatedEntityId
	}
	return ""
}

func (x *CalendarEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CalendarEvent) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *CalendarEvent) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CalendarEvent) GetReminderMinutesBefore() int32 {
	if x != nil {
		return x.ReminderMinutesBefore
	}
	return 0
}

func (x *CalendarEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CalendarEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CalendarEvent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListMyCalendarEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyCalendarEventsRequest) Reset() {
	*x = ListMyCalendarEventsRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyCalendarEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyCalendarEventsRequest) ProtoMessage() {}

func (x *ListMyCalendarEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyCalendarEventsRequest.ProtoReflect.Descriptor instead.
func (*ListMyCalendarEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyCalendarEventsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListMyCalendarEventsRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *ListMyCalendarEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ListCalendarEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CalendarEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCalendarEventsResponse) Reset() {
	*x = ListCalendarEventsResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalendarEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalendarEventsResponse) ProtoMessage() {}

func (x *ListCalendarEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalendarEventsResponse.ProtoReflect.Descriptor instead.
func (*ListCalendarEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *ListCalendarEventsResponse) GetEvents() []*CalendarEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetCalendarEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCalendarEventRequest) Reset() {
	*x = GetCalendarEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCalendarEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCalendarEventRequest) ProtoMessage() {}

func (x *GetCalendarEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCalendarEventRequest.ProtoReflect.Descriptor instead.
func (*GetCalendarEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *GetCalendarEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CalendarEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *CalendarEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarEventResponse) Reset() {
	*x = CalendarEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarEventResponse) ProtoMessage() {}

func (x *CalendarEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarEventResponse.ProtoReflect.Descriptor instead.
func (*CalendarEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *CalendarEventResponse) GetEvent() *CalendarEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateCalendarEventRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Title                 string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	EventType             string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	StartsAt              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt                *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Timezone              string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Location              string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	MeetingUrl            string                 `protobuf:"bytes,8,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	RelatedEntityType     string                 `protobuf:"bytes,9,opt,name=related_entity_type,json=relatedEntityType,proto3" json:"related_entity_type,omitempty"`
	RelatedEntityId       string                 `protobuf:"bytes,10,opt,name=related_entity_id,json=relatedEntityId,proto3" json:"related_entity_id,omitempty"`
	JobId                 string                 `protobuf:"bytes,11,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobTitle              string                 `protobuf:"bytes,12,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Company               string                 `protobuf:"bytes,13,opt,name=company,proto3" json:"company,omitempty"`
	ReminderMinutesBefore int32                  `protobuf:"varint,14,opt,name=reminder_minutes_before,json=reminderMinutesBefore,proto3" json:"reminder_minutes_before,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateCalendarEventRequest) Reset() {
	*x = CreateCalendarEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCalendarEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCalendarEventRequest) ProtoMessage() {}

func (x *CreateCalendarEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCalendarEventRequest.ProtoReflect.Descriptor instead.
func (*CreateCalendarEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCalendarEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CreateCalendarEventRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *CreateCalendarEventRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetRelatedEntityType() string {
	if x != nil {
		return x.RelatedEntityType
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetRelatedEntityId() string {
	if x != nil {
		return x.RelatedEntityId
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateCalendarEventRequest) GetReminderMinutesBefore() int32 {
	if x != nil {
		return x.ReminderMinutesBefore
	}
	return 0
}

type UpdateCalendarEventRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EventType             string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	StartsAt              *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt                *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Timezone              string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Location              string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	MeetingUrl            string                 `protobuf:"bytes,9,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	ReminderMinutesBefore int32                  `protobuf:"varint,10,opt,name=reminder_minutes_before,json=reminderMinutesBefore,proto3" json:"reminder_minutes_before,omitempty"`
	Status                string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateCalendarEventRequest) Reset() {
	*x = UpdateCalendarEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCalendarEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCalendarEventRequest) ProtoMessage() {}

func (x *UpdateCalendarEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCalendarEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateCalendarEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCalendarEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *UpdateCalendarEventRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *UpdateCalendarEventRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *UpdateCalendarEventRequest) GetReminderMinutesBefore() int32 {
	if x != nil {
		return x.ReminderMinutesBefore
	}
	return 0
}

func (x *UpdateCalendarEventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteCalendarEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCalendarEventRequest) Reset() {
	*x = DeleteCalendarEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCalendarEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCalendarEventRequest) ProtoMessage() {}

func (x *DeleteCalendarEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCalendarEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteCalendarEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCalendarEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCalendarEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCalendarEventResponse) Reset() {
	*x = DeleteCalendarEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCalendarEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCalendarEventResponse) ProtoMessage() {}

func (x *DeleteCalendarEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCalendarEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteCalendarEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCalendarEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_calendar_calendar_proto protoreflect.FileDescriptor

const file_proto_calendar_calendar_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/calendar/calendar.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x05\n" +
	"\rCalendarEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x127\n" +
	"\tstarts_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12\x1f\n" +
	"\vmeeting_url\x18\n" +
	" \x01(\tR\n" +
	"meetingUrl\x12.\n" +
	"\x13related_entity_type\x18\v \x01(\tR\x11relatedEntityType\x12*\n" +
	"\x11related_entity_id\x18\f \x01(\tR\x0frelatedEntityId\x12\x15\n" +
	"\x06job_id\x18\r \x01(\tR\x05jobId\x12\x1b\n" +
	"\tjob_title\x18\x0e \x01(\tR\bjobTitle\x12\x18\n" +
	"\acompany\x18\x0f \x01(\tR\acompany\x126\n" +
	"\x17reminder_minutes_before\x18\x10 \x01(\x05R\x15reminderMinutesBefore\x12\x16\n" +
	"\x06status\x18\x11 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x01\n" +
	"\x1bListMyCalendarEventsRequest\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\"M\n" +
	"\x1aListCalendarEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.calendar.CalendarEventR\x06events\")\n" +
	"\x17GetCalendarEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x15CalendarEventResponse\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.calendar.CalendarEventR\x05event\"\x9c\x04\n" +
	"\x1aCreateCalendarEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x127\n" +
	"\tstarts_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1f\n" +
	"\vmeeting_url\x18\b \x01(\tR\n" +
	"meetingUrl\x12.\n" +
	"\x13related_entity_type\x18\t \x01(\tR\x11relatedEntityType\x12*\n" +
	"\x11related_entity_id\x18\n" +
	" \x01(\tR\x0frelatedEntityId\x12\x15\n" +
	"\x06job_id\x18\v \x01(\tR\x05jobId\x12\x1b\n" +
	"\tjob_title\x18\f \x01(\tR\bjobTitle\x12\x18\n" +
	"\acompany\x18\r \x01(\tR\acompany\x126\n" +
	"\x17reminder_minutes_before\x18\x0e \x01(\x05R\x15reminderMinutesBefore\"\x9a\x03\n" +
	"\x1aUpdateCalendarEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x1f\n" +
	"\vmeeting_url\x18\t \x01(\tR\n" +
	"meetingUrl\x126\n" +
	"\x17reminder_minutes_before\x18\n" +
	" \x01(\x05R\x15reminderMinutesBefore\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\",\n" +
	"\x1aDeleteCalendarEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x1bDeleteCalendarEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf0\x03\n" +
	"\x0fCalendarService\x12c\n" +
	"\x14ListMyCalendarEvents\x12%.calendar.ListMyCalendarEventsRequest\x1a$.calendar.ListCalendarEventsResponse\x12X\n" +
	"\x12GetMyCalendarEvent\x12!.calendar.GetCalendarEventRequest\x1a\x1f.calendar.CalendarEventResponse\x12\\\n" +
	"\x13CreateCalendarEvent\x12$.calendar.CreateCalendarEventRequest\x1a\x1f.calendar.CalendarEventResponse\x12\\\n" +
	"\x13UpdateCalendarEvent\x12$.calendar.UpdateCalendarEventRequest\x1a\x1f.calendar.CalendarEventResponse\x12b\n" +
	"\x13DeleteCalendarEvent\x12$.calendar.DeleteCalendarEventRequest\x1a%.calendar.DeleteCalendarEventResponseBYZWgithub.com/kaansari/ceerat-platform/packages/ceerat-contracts/proto/calendar;calendarpbb\x06proto3"

var (
	file_proto_calendar_calendar_proto_rawDescOnce sync.Once
	file_proto_calendar_calendar_proto_rawDescData []byte
)

func file_proto_calendar_calendar_proto_rawDescGZIP() []byte {
	file_proto_calendar_calendar_proto_rawDescOnce.Do(func() {
		file_proto_calendar_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)))
	})
	return file_proto_calendar_calendar_proto_rawDescData
}

var file_proto_calendar_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_calendar_calendar_proto_goTypes = []any{
	(*CalendarEvent)(nil),               // 0: calendar.CalendarEvent
	(*ListMyCalendarEventsRequest)(nil), // 1: calendar.ListMyCalendarEventsRequest
	(*ListCalendarEventsResponse)(nil),  // 2: calendar.ListCalendarEventsResponse
	(*GetCalendarEventRequest)(nil),     // 3: calendar.GetCalendarEventRequest
	(*CalendarEventResponse)(nil),       // 4: calendar.CalendarEventResponse
	(*CreateCalendarEventRequest)(nil),  // 5: calendar.CreateCalendarEventRequest
	(*UpdateCalendarEventRequest)(nil),  // 6: calendar.UpdateCalendarEventRequest
	(*DeleteCalendarEventRequest)(nil),  // 7: calendar.DeleteCalendarEventRequest
	(*DeleteCalendarEventResponse)(nil), // 8: calendar.DeleteCalendarEventResponse
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_proto_calendar_calendar_proto_depIdxs = []int32{
	9,  // 0: calendar.CalendarEvent.starts_at:type_name -> google.protobuf.Timestamp
	9,  // 1: calendar.CalendarEvent.ends_at:type_name -> google.protobuf.Timestamp
	9,  // 2: calendar.CalendarEvent.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: calendar.CalendarEvent.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 4: calendar.ListMyCalendarEventsRequest.start:type_name -> google.protobuf.Timestamp
	9,  // 5: calendar.ListMyCalendarEventsRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 6: calendar.ListCalendarEventsResponse.events:type_name -> calendar.CalendarEvent
	0,  // 7: calendar.CalendarEventResponse.event:type_name -> calendar.CalendarEvent
	9,  // 8: calendar.CreateCalendarEventRequest.starts_at:type_name -> google.protobuf.Timestamp
	9,  // 9: calendar.CreateCalendarEventRequest.ends_at:type_name -> google.protobuf.Timestamp
	9,  // 10: calendar.UpdateCalendarEventRequest.starts_at:type_name -> google.protobuf.Timestamp
	9,  // 11: calendar.UpdateCalendarEventRequest.ends_at:type_name -> google.protobuf.Timestamp
	1,  // 12: calendar.CalendarService.ListMyCalendarEvents:input_type -> calendar.ListMyCalendarEventsRequest
	3,  // 13: calendar.CalendarService.GetMyCalendarEvent:input_type -> calendar.GetCalendarEventRequest
	5,  // 14: calendar.CalendarService.CreateCalendarEvent:input_type -> calendar.CreateCalendarEventRequest
	6,  // 15: calendar.CalendarService.UpdateCalendarEvent:input_type -> calendar.UpdateCalendarEventRequest
	7,  // 16: calendar.CalendarService.DeleteCalendarEvent:input_type -> calendar.DeleteCalendarEventRequest
	2,  // 17: calendar.CalendarService.ListMyCalendarEvents:output_type -> calendar.ListCalendarEventsResponse
	4,  // 18: calendar.CalendarService.GetMyCalendarEvent:output_type -> calendar.CalendarEventResponse
	4,  // 19: calendar.CalendarService.CreateCalendarEvent:output_type -> calendar.CalendarEventResponse
	4,  // 20: calendar.CalendarService.UpdateCalendarEvent:output_type -> calendar.CalendarEventResponse
	8,  // 21: calendar.CalendarService.DeleteCalendarEvent:output_type -> calendar.DeleteCalendarEventResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_calendar_calendar_proto_init() }
func file_proto_calendar_calendar_proto_init() {
	if File_proto_calendar_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_calendar_proto_goTypes,
		DependencyIndexes: file_proto_calendar_calendar_proto_depIdxs,
		MessageInfos:      file_proto_calendar_calendar_proto_msgTypes,
	}.Build()
	File_proto_calendar_calendar_proto = out.File
	file_proto_calendar_calendar_proto_goTypes = nil
	file_proto_calendar_calendar_proto_depIdxs = nil
}
