// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.8.0
// source: proto/order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderManagerClient is the client API for OrderManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderManagerClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	CreateMyOrder(ctx context.Context, in *CreateMyOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	GetMyOrder(ctx context.Context, in *GetMyOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	ListMyOrders(ctx context.Context, in *ListMyOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error)
	AddServiceToOrder(ctx context.Context, in *AddServiceToOrderRequest, opts ...grpc.CallOption) (*AddServiceToOrderResponse, error)
	RemoveServiceFromOrder(ctx context.Context, in *RemoveServiceFromOrderRequest, opts ...grpc.CallOption) (*RemoveServiceFromOrderResponse, error)
	CheckoutMyCart(ctx context.Context, in *CheckoutMyCartRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	QuoteMyCartPricing(ctx context.Context, in *QuoteMyCartPricingRequest, opts ...grpc.CallOption) (*OrderPricingQuoteResponse, error)
	RepriceOrder(ctx context.Context, in *RepriceOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	CreateOrderPricingRule(ctx context.Context, in *OrderPricingRuleRequest, opts ...grpc.CallOption) (*OrderPricingRuleResponse, error)
	ListOrderPricingRules(ctx context.Context, in *ListOrderPricingRulesRequest, opts ...grpc.CallOption) (*ListOrderPricingRulesResponse, error)
	UpdateOrderPricingRule(ctx context.Context, in *OrderPricingRuleRequest, opts ...grpc.CallOption) (*OrderPricingRuleResponse, error)
	DeleteOrderPricingRule(ctx context.Context, in *DeleteOrderPricingRuleRequest, opts ...grpc.CallOption) (*DeleteOrderPricingRuleResponse, error)
	CreatePaymentSession(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*PaymentSessionResponse, error)
	GetMyPaymentSession(ctx context.Context, in *GetPaymentSessionRequest, opts ...grpc.CallOption) (*PaymentSessionResponse, error)
}

type orderManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderManagerClient(cc grpc.ClientConnInterface) OrderManagerClient {
	return &orderManagerClient{cc}
}

func (c *orderManagerClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) CreateMyOrder(ctx context.Context, in *CreateMyOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/CreateMyOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) GetMyOrder(ctx context.Context, in *GetMyOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/GetMyOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/ListOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) ListMyOrders(ctx context.Context, in *ListMyOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/ListMyOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error) {
	out := new(UpdateOrderStatusResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/UpdateOrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) AddServiceToOrder(ctx context.Context, in *AddServiceToOrderRequest, opts ...grpc.CallOption) (*AddServiceToOrderResponse, error) {
	out := new(AddServiceToOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/AddServiceToOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) RemoveServiceFromOrder(ctx context.Context, in *RemoveServiceFromOrderRequest, opts ...grpc.CallOption) (*RemoveServiceFromOrderResponse, error) {
	out := new(RemoveServiceFromOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/RemoveServiceFromOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) CheckoutMyCart(ctx context.Context, in *CheckoutMyCartRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/CheckoutMyCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) QuoteMyCartPricing(ctx context.Context, in *QuoteMyCartPricingRequest, opts ...grpc.CallOption) (*OrderPricingQuoteResponse, error) {
	out := new(OrderPricingQuoteResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/QuoteMyCartPricing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) RepriceOrder(ctx context.Context, in *RepriceOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/RepriceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) CreateOrderPricingRule(ctx context.Context, in *OrderPricingRuleRequest, opts ...grpc.CallOption) (*OrderPricingRuleResponse, error) {
	out := new(OrderPricingRuleResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/CreateOrderPricingRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) ListOrderPricingRules(ctx context.Context, in *ListOrderPricingRulesRequest, opts ...grpc.CallOption) (*ListOrderPricingRulesResponse, error) {
	out := new(ListOrderPricingRulesResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/ListOrderPricingRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) UpdateOrderPricingRule(ctx context.Context, in *OrderPricingRuleRequest, opts ...grpc.CallOption) (*OrderPricingRuleResponse, error) {
	out := new(OrderPricingRuleResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/UpdateOrderPricingRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) DeleteOrderPricingRule(ctx context.Context, in *DeleteOrderPricingRuleRequest, opts ...grpc.CallOption) (*DeleteOrderPricingRuleResponse, error) {
	out := new(DeleteOrderPricingRuleResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/DeleteOrderPricingRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) CreatePaymentSession(ctx context.Context, in *CreatePaymentSessionRequest, opts ...grpc.CallOption) (*PaymentSessionResponse, error) {
	out := new(PaymentSessionResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/CreatePaymentSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderManagerClient) GetMyPaymentSession(ctx context.Context, in *GetPaymentSessionRequest, opts ...grpc.CallOption) (*PaymentSessionResponse, error) {
	out := new(PaymentSessionResponse)
	err := c.cc.Invoke(ctx, "/order.OrderManager/GetMyPaymentSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderManagerServer is the server API for OrderManager service.
// All implementations must embed UnimplementedOrderManagerServer
// for forward compatibility
type OrderManagerServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	CreateMyOrder(context.Context, *CreateMyOrderRequest) (*CreateOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetMyOrder(context.Context, *GetMyOrderRequest) (*GetOrderResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	ListMyOrders(context.Context, *ListMyOrdersRequest) (*ListOrdersResponse, error)
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
	AddServiceToOrder(context.Context, *AddServiceToOrderRequest) (*AddServiceToOrderResponse, error)
	RemoveServiceFromOrder(context.Context, *RemoveServiceFromOrderRequest) (*RemoveServiceFromOrderResponse, error)
	CheckoutMyCart(context.Context, *CheckoutMyCartRequest) (*CreateOrderResponse, error)
	QuoteMyCartPricing(context.Context, *QuoteMyCartPricingRequest) (*OrderPricingQuoteResponse, error)
	RepriceOrder(context.Context, *RepriceOrderRequest) (*CreateOrderResponse, error)
	CreateOrderPricingRule(context.Context, *OrderPricingRuleRequest) (*OrderPricingRuleResponse, error)
	ListOrderPricingRules(context.Context, *ListOrderPricingRulesRequest) (*ListOrderPricingRulesResponse, error)
	UpdateOrderPricingRule(context.Context, *OrderPricingRuleRequest) (*OrderPricingRuleResponse, error)
	DeleteOrderPricingRule(context.Context, *DeleteOrderPricingRuleRequest) (*DeleteOrderPricingRuleResponse, error)
	CreatePaymentSession(context.Context, *CreatePaymentSessionRequest) (*PaymentSessionResponse, error)
	GetMyPaymentSession(context.Context, *GetPaymentSessionRequest) (*PaymentSessionResponse, error)
	mustEmbedUnimplementedOrderManagerServer()
}

// UnimplementedOrderManagerServer must be embedded to have forward compatible implementations.
type UnimplementedOrderManagerServer struct {
}

func (UnimplementedOrderManagerServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderManagerServer) CreateMyOrder(context.Context, *CreateMyOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMyOrder not implemented")
}
func (UnimplementedOrderManagerServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderManagerServer) GetMyOrder(context.Context, *GetMyOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyOrder not implemented")
}
func (UnimplementedOrderManagerServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderManagerServer) ListMyOrders(context.Context, *ListMyOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyOrders not implemented")
}
func (UnimplementedOrderManagerServer) UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (UnimplementedOrderManagerServer) AddServiceToOrder(context.Context, *AddServiceToOrderRequest) (*AddServiceToOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddServiceToOrder not implemented")
}
func (UnimplementedOrderManagerServer) RemoveServiceFromOrder(context.Context, *RemoveServiceFromOrderRequest) (*RemoveServiceFromOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveServiceFromOrder not implemented")
}
func (UnimplementedOrderManagerServer) CheckoutMyCart(context.Context, *CheckoutMyCartRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckoutMyCart not implemented")
}
func (UnimplementedOrderManagerServer) QuoteMyCartPricing(context.Context, *QuoteMyCartPricingRequest) (*OrderPricingQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteMyCartPricing not implemented")
}
func (UnimplementedOrderManagerServer) RepriceOrder(context.Context, *RepriceOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepriceOrder not implemented")
}
func (UnimplementedOrderManagerServer) CreateOrderPricingRule(context.Context, *OrderPricingRuleRequest) (*OrderPricingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrderPricingRule not implemented")
}
func (UnimplementedOrderManagerServer) ListOrderPricingRules(context.Context, *ListOrderPricingRulesRequest) (*ListOrderPricingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrderPricingRules not implemented")
}
func (UnimplementedOrderManagerServer) UpdateOrderPricingRule(context.Context, *OrderPricingRuleRequest) (*OrderPricingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderPricingRule not implemented")
}
func (UnimplementedOrderManagerServer) DeleteOrderPricingRule(context.Context, *DeleteOrderPricingRuleRequest) (*DeleteOrderPricingRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrderPricingRule not implemented")
}
func (UnimplementedOrderManagerServer) CreatePaymentSession(context.Context, *CreatePaymentSessionRequest) (*PaymentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePaymentSession not implemented")
}
func (UnimplementedOrderManagerServer) GetMyPaymentSession(context.Context, *GetPaymentSessionRequest) (*PaymentSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyPaymentSession not implemented")
}
func (UnimplementedOrderManagerServer) mustEmbedUnimplementedOrderManagerServer() {}

// UnsafeOrderManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderManagerServer will
// result in compilation errors.
type UnsafeOrderManagerServer interface {
	mustEmbedUnimplementedOrderManagerServer()
}

func RegisterOrderManagerServer(s grpc.ServiceRegistrar, srv OrderManagerServer) {
	s.RegisterService(&OrderManager_ServiceDesc, srv)
}

func _OrderManager_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_CreateMyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).CreateMyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/CreateMyOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).CreateMyOrder(ctx, req.(*CreateMyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_GetMyOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).GetMyOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/GetMyOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).GetMyOrder(ctx, req.(*GetMyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/ListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_ListMyOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).ListMyOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/ListMyOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).ListMyOrders(ctx, req.(*ListMyOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/UpdateOrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_AddServiceToOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServiceToOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).AddServiceToOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/AddServiceToOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).AddServiceToOrder(ctx, req.(*AddServiceToOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_RemoveServiceFromOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServiceFromOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).RemoveServiceFromOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/RemoveServiceFromOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).RemoveServiceFromOrder(ctx, req.(*RemoveServiceFromOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_CheckoutMyCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutMyCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).CheckoutMyCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/CheckoutMyCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).CheckoutMyCart(ctx, req.(*CheckoutMyCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_QuoteMyCartPricing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteMyCartPricingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).QuoteMyCartPricing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/QuoteMyCartPricing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).QuoteMyCartPricing(ctx, req.(*QuoteMyCartPricingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_RepriceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepriceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).RepriceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/RepriceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).RepriceOrder(ctx, req.(*RepriceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_CreateOrderPricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).CreateOrderPricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/CreateOrderPricingRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).CreateOrderPricingRule(ctx, req.(*OrderPricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_ListOrderPricingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderPricingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).ListOrderPricingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/ListOrderPricingRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).ListOrderPricingRules(ctx, req.(*ListOrderPricingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_UpdateOrderPricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).UpdateOrderPricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/UpdateOrderPricingRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).UpdateOrderPricingRule(ctx, req.(*OrderPricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_DeleteOrderPricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderPricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).DeleteOrderPricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/DeleteOrderPricingRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).DeleteOrderPricingRule(ctx, req.(*DeleteOrderPricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_CreatePaymentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).CreatePaymentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/CreatePaymentSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).CreatePaymentSession(ctx, req.(*CreatePaymentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderManager_GetMyPaymentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServer).GetMyPaymentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderManager/GetMyPaymentSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServer).GetMyPaymentSession(ctx, req.(*GetPaymentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderManager_ServiceDesc is the grpc.ServiceDesc for OrderManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderManager",
	HandlerType: (*OrderManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderManager_CreateOrder_Handler,
		},
		{
			MethodName: "CreateMyOrder",
			Handler:    _OrderManager_CreateMyOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderManager_GetOrder_Handler,
		},
		{
			MethodName: "GetMyOrder",
			Handler:    _OrderManager_GetMyOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderManager_ListOrders_Handler,
		},
		{
			MethodName: "ListMyOrders",
			Handler:    _OrderManager_ListMyOrders_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _OrderManager_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "AddServiceToOrder",
			Handler:    _OrderManager_AddServiceToOrder_Handler,
		},
		{
			MethodName: "RemoveServiceFromOrder",
			Handler:    _OrderManager_RemoveServiceFromOrder_Handler,
		},
		{
			MethodName: "CheckoutMyCart",
			Handler:    _OrderManager_CheckoutMyCart_Handler,
		},
		{
			MethodName: "QuoteMyCartPricing",
			Handler:    _OrderManager_QuoteMyCartPricing_Handler,
		},
		{
			MethodName: "RepriceOrder",
			Handler:    _OrderManager_RepriceOrder_Handler,
		},
		{
			MethodName: "CreateOrderPricingRule",
			Handler:    _OrderManager_CreateOrderPricingRule_Handler,
		},
		{
			MethodName: "ListOrderPricingRules",
			Handler:    _OrderManager_ListOrderPricingRules_Handler,
		},
		{
			MethodName: "UpdateOrderPricingRule",
			Handler:    _OrderManager_UpdateOrderPricingRule_Handler,
		},
		{
			MethodName: "DeleteOrderPricingRule",
			Handler:    _OrderManager_DeleteOrderPricingRule_Handler,
		},
		{
			MethodName: "CreatePaymentSession",
			Handler:    _OrderManager_CreatePaymentSession_Handler,
		},
		{
			MethodName: "GetMyPaymentSession",
			Handler:    _OrderManager_GetMyPaymentSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/order/order.proto",
}
