package security

var KnownGRPCMethods = []string{
	"/auth.Auth/Create",
	"/auth.Auth/RegisterCustomer",
	"/auth.Auth/Get",
	"/auth.Auth/GetAll",
	"/auth.Auth/Auth",
	"/auth.Auth/ValidateToken",
	"/auth.Auth/UpdateProfile",
	"/auth.Auth/UpdatePassword",
	"/customer.CustomerService/CreateCustomer",
	"/customer.CustomerService/GetCustomer",
	"/customer.CustomerService/GetMyCustomerProfile",
	"/customer.CustomerService/ListCustomers",
	"/customer.CustomerService/UpdateCustomer",
	"/customer.CustomerService/UpdateMyCustomerProfile",
	"/customer.CustomerService/DeleteCustomer",
	"/customer.CustomerService/AssignCustomerToUser",
	"/service.ServiceManager/CreateService",
	"/service.ServiceManager/GetService",
	"/service.ServiceManager/ListServices",
	"/service.ServiceManager/UpdateService",
	"/service.ServiceManager/DeleteService",
	"/service.ServiceManager/AssignServiceToCustomer",
	"/service.ServiceManager/GetCustomerService",
	"/service.ServiceManager/ListCustomerServices",
	"/service.ServiceManager/UpdateCustomerService",
	"/service.ServiceManager/RemoveServiceFromCustomer",
	"/order.OrderManager/CreateOrder",
	"/order.OrderManager/CreateMyOrder",
	"/order.OrderManager/GetOrder",
	"/order.OrderManager/GetMyOrder",
	"/order.OrderManager/ListOrders",
	"/order.OrderManager/ListMyOrders",
	"/order.OrderManager/UpdateOrderStatus",
	"/order.OrderManager/AddServiceToOrder",
	"/order.OrderManager/RemoveServiceFromOrder",
	"/patient.patient/Create",
	"/patient.patient/Get",
	"/patient.patient/GetAll",
	"/patient.patient/Auth",
	"/patient.patient/ValidateToken",
}

var DefaultRolePermissions = map[string][]string{
	"admin": {"*"},
	"agent": {
		"/customer.CustomerService/CreateCustomer",
		"/customer.CustomerService/GetCustomer",
		"/customer.CustomerService/ListCustomers",
		"/customer.CustomerService/UpdateCustomer",
		"/service.ServiceManager/ListServices",
		"/service.ServiceManager/AssignServiceToCustomer",
		"/order.OrderManager/CreateOrder",
		"/order.OrderManager/GetOrder",
		"/order.OrderManager/ListOrders",
		"/order.OrderManager/AddServiceToOrder",
		"/order.OrderManager/UpdateOrderStatus",
	},
	"customer": {
		"/auth.Auth/Get",
		"/auth.Auth/GetAll",
		"/auth.Auth/UpdateProfile",
		"/auth.Auth/UpdatePassword",
		"/customer.CustomerService/CreateCustomer",
		"/customer.CustomerService/GetCustomer",
		"/customer.CustomerService/GetMyCustomerProfile",
		"/customer.CustomerService/UpdateMyCustomerProfile",
		"/service.ServiceManager/ListServices",
		"/service.ServiceManager/GetCustomerService",
		"/service.ServiceManager/ListCustomerServices",
		"/order.OrderManager/GetOrder",
		"/order.OrderManager/GetMyOrder",
		"/order.OrderManager/ListOrders",
		"/order.OrderManager/ListMyOrders",
		"/order.OrderManager/CreateMyOrder",
	},
}
